-- Create role enum
CREATE TYPE public.app_role AS ENUM ('admin', 'user');

-- Create profiles table
CREATE TABLE public.profiles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL UNIQUE,
  name VARCHAR(120),
  email VARCHAR(190),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Create user_roles table
CREATE TABLE public.user_roles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  role app_role NOT NULL DEFAULT 'user',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id, role)
);

-- Create polls table
CREATE TABLE public.polls (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question VARCHAR(255) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Create poll_options table
CREATE TABLE public.poll_options (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  poll_id BIGINT REFERENCES public.polls(id) ON DELETE CASCADE NOT NULL,
  option_text VARCHAR(255) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Create votes table (active votes with IP restriction)
CREATE TABLE public.votes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  poll_id BIGINT REFERENCES public.polls(id) ON DELETE CASCADE NOT NULL,
  option_id BIGINT REFERENCES public.poll_options(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  ip_address VARCHAR(64) NOT NULL,
  voted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (poll_id, ip_address)
);

-- Create vote_histories table (audit log)
CREATE TABLE public.vote_histories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  poll_id BIGINT NOT NULL,
  user_id UUID,
  ip_address VARCHAR(64) NOT NULL,
  old_option_id BIGINT,
  new_option_id BIGINT,
  action VARCHAR(20) NOT NULL CHECK (action IN ('VOTE', 'RELEASE', 'REVOTE')),
  old_voted_at TIMESTAMPTZ,
  new_voted_at TIMESTAMPTZ,
  performed_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Enable RLS on all tables
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.polls ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.poll_options ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.votes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vote_histories ENABLE ROW LEVEL SECURITY;

-- Security definer function to check roles
CREATE OR REPLACE FUNCTION public.has_role(_user_id UUID, _role app_role)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.user_roles
    WHERE user_id = _user_id AND role = _role
  )
$$;

-- Profiles policies
CREATE POLICY "Users can view their own profile" ON public.profiles
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can update their own profile" ON public.profiles
  FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own profile" ON public.profiles
  FOR INSERT WITH CHECK (auth.uid() = user_id);

-- User roles policies
CREATE POLICY "Users can view their own roles" ON public.user_roles
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Admins can view all roles" ON public.user_roles
  FOR SELECT USING (public.has_role(auth.uid(), 'admin'));

-- Polls policies
CREATE POLICY "Authenticated users can view active polls" ON public.polls
  FOR SELECT TO authenticated USING (status = 'active' OR public.has_role(auth.uid(), 'admin'));

CREATE POLICY "Admins can create polls" ON public.polls
  FOR INSERT TO authenticated WITH CHECK (public.has_role(auth.uid(), 'admin'));

CREATE POLICY "Admins can update polls" ON public.polls
  FOR UPDATE TO authenticated USING (public.has_role(auth.uid(), 'admin'));

-- Poll options policies
CREATE POLICY "Authenticated users can view poll options" ON public.poll_options
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "Admins can manage poll options" ON public.poll_options
  FOR ALL TO authenticated USING (public.has_role(auth.uid(), 'admin'));

-- Votes policies
CREATE POLICY "Authenticated users can view vote counts" ON public.votes
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "Authenticated users can insert their vote" ON public.votes
  FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Admins can delete votes (release IP)" ON public.votes
  FOR DELETE TO authenticated USING (public.has_role(auth.uid(), 'admin'));

-- Vote histories policies
CREATE POLICY "Admins can view vote history" ON public.vote_histories
  FOR SELECT TO authenticated USING (public.has_role(auth.uid(), 'admin'));

CREATE POLICY "System can insert vote history" ON public.vote_histories
  FOR INSERT TO authenticated WITH CHECK (true);

-- Function to handle profile creation on signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (user_id, email)
  VALUES (NEW.id, NEW.email);
  
  INSERT INTO public.user_roles (user_id, role)
  VALUES (NEW.id, 'user');
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- Trigger for new user signup
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Enable realtime for votes table
ALTER PUBLICATION supabase_realtime ADD TABLE public.votes;